[WIP ] Add ConfigurationVersions
everis-technology/Tfe.NetClient pull request #6
Opened 2021-03-25 09:06 UTC by mortengjesing

# Description

Added ConfigurationVersions methods.

Changed the client to handle Kabab case without adding `JsonPropertyName` attribute to every property

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [] Extended the documentation

2021-03-25 16:41 UTC, cmendible commented on src/Tfe.NetClient/Features/JsonKebabCaseNamingPolicy.cs
> +    public class JsonKebabCaseNamingPolicy : JsonNamingPolicy
Nice!

2021-03-25 16:46 UTC, cmendible requested changes
Can you split the PR so we add the JsonKebabCaseNamingPolicy feature in one PR and the ConfigurationVersion and tests in other?

2021-03-25 19:36 UTC, mortengjesing commented
Would like to avoid to implement the JsonPropertyName on ConfigurationVersions if possible. Why would you like to split it? Maybe I can come up with a solution to your concerns.

2021-04-04 10:07 UTC, cmendible commented
Forget about splitting the PW I'm approving it as is.

2021-04-04 10:08 UTC, merged